### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by ptzld** [Arnavion/tpfancontrol-rs#7]
mismatched types
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.10.0/src/backend/termion.rs:222:46
    |
222 |           let terminal = AlternateScreen::from(MouseTerminal::from(
    |  ______________________________________________^
223 | |             ::std::io::stdout().into_raw_mode().unwrap(),
224 | |         ));
    | |_________^ expected struct `AlternateScreen`, found struct `MouseTerminal`
    |
    = note: expected struct `AlternateScreen<_>`
               found struct `MouseTerminal<RawTerminal<Stdout>>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `cursive` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by Arnavion** [comment]
Well, that's a bug in cursive or termion that one of them didn't handle semver correctly. But of course this repo is using 2-year-old versions so there's no point reporting it to them.

I don't maintain this any more since my ThinkPad spends most of its time turned off these days, but I'll see how much effort it is to just update deps to latest.

**Comment by Arnavion** [comment]
Actually, it still repros with cursive 0.20.0 and termion 1.6.0. Turns out it's a semver-breaking API change in termion 1.6.0 - https://gitlab.redox-os.org/redox-os/termion/-/commit/0082c8da04f861b677dee1e8da9c56bdffd3f422 removed `AlternateScreen::from`

@jackpot51 FYI

**Comment by jackpot51** [comment]
I yanked 1.6.0 and will re-release as 2.0.0, thanks for the notice.

**Comment by jackpot51** [comment]
Done, with migration guide: https://crates.io/crates/termion
